name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on: push

jobs:
  build:
    name: Create Release
    runs-on: windows-2019
    env:
      targetZip: bazel-msys2-x86_64-posix-seh-rev0-8.1.0.zip
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
        # msys64
      - name: curl msys2-base-x86_64.sfx.exe and unzip
        shell: cmd
        run: |
          cd /d ${{ github.workspace }} &&^
          curl https://github.com/msys2/msys2-installer/releases/download/2022-10-28/msys2-base-x86_64-20221028.sfx.exe -L --output msys2-base-x86_64.sfx.exe &&^
          dir &&^
          msys2-base-x86_64.sfx.exe -y
        
#       - name: curl cmake-3.24.0-windows-x86_64.zip
#         shell: cmd
#         run: |
#           cd /d ${{ github.workspace }} &&^
#           curl https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-x86_64.zip -L --output cmake-3.24.0-windows-x86_64.zip &&^
#           dir &&^
#           7z.exe x cmake-3.24.0-windows-x86_64.zip
      
      - name: curl x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
        shell: cmd
        run: |
          cd /d ${{ github.workspace }} &&^
          curl https://github.com/2641797006/c/blob/master/GCC-zip/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z?raw=true -L --output x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z &&^
          dir &&^
          7z.exe x x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z -o"${{ github.workspace }}\x86_64-8.1.0-release-posix-seh-rt_v6-rev0" &&^
          cd /d "${{ github.workspace }}\x86_64-8.1.0-release-posix-seh-rt_v6-rev0" &&^
          xcopy /E /H /Y /C ".\mingw64\*" "msys64\mingw64\"
        
        # msys64\jdk-11.0.1
      - name: curl openjdk-11.0.1_windows-x64_bin.zip
        shell: cmd
        run: |
          cd /d ${{ github.workspace }}\msys64\ &&^ 
          curl https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_windows-x64_bin.zip -L --output openjdk-11.0.1_windows-x64_bin.zip &&^
          dir &&^
          7z.exe x openjdk-11.0.1_windows-x64_bin.zip
          
        # msys64\mingw64\bin\bazel.exe
      - name: curl bazel-5.3.2-windows-x86_64.exe
        shell: cmd
        run: |
          cd /d ${{ github.workspace }}\msys64\mingw64\bin\ &&^ 
          curl https://github.com/bazelbuild/bazel/releases/download/5.3.2/bazel-5.3.2-windows-x86_64.exe -L --output bazel.exe &&^
          
      - name: Copy local-build.sh template
        shell: cmd
        run: cd /d ${{ github.workspace }}\bazel-msys2-mingw64" && xcopy /H /Y /C ".\run.sh" "${{ github.workspace }}\msys64"
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "msys64"
          filename: "${{ env.mingwTargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "msys64/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
